//! Bundle creation and reading — packages credentials into various export formats.

use crate::crypto::bundle::{decrypt_bundle, encrypt_bundle};
use crate::types::*;
use crate::{Error, Result};
use chrono::Utc;
use secrecy::{ExposeSecret, SecretString};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Internal serialized format for the encrypted payload.
#[derive(Serialize, Deserialize)]
struct BundlePayload {
    label: String,
    created: String,
    expires: Option<String>,
    bundle_id: String,
    credentials: Vec<PayloadCredential>,
}

#[derive(Serialize, Deserialize)]
struct PayloadCredential {
    domain: String,
    url: Option<String>,
    username: Option<String>,
    password: String,
    credential_type: CredentialType,
    label: Option<String>,
}

/// Create a bundle from extracted credentials.
pub fn create_bundle(credentials: &[Credential], options: &BundleOptions) -> Result<Vec<u8>> {
    match options.format {
        BundleFormat::CredVault => create_credvault_bundle(credentials, options),
        BundleFormat::Csv => create_csv_bundle(credentials),
        BundleFormat::Env => create_env_bundle(credentials),
        BundleFormat::AgentConfig => create_agent_config_bundle(credentials, options),
    }
}

/// Read and decrypt a CredVault bundle.
pub fn read_bundle(data: &[u8], password: &SecretString) -> Result<BundleContents> {
    let plaintext = decrypt_bundle(data, password)?;

    let payload: BundlePayload = rmp_serde::from_slice(&plaintext)
        .map_err(|e| Error::InvalidBundle(format!("Failed to deserialize bundle: {e}")))?;

    let created = chrono::DateTime::parse_from_rfc3339(&payload.created)
        .map_err(|e| Error::InvalidBundle(format!("Invalid created timestamp: {e}")))?
        .with_timezone(&Utc);

    let expires = payload
        .expires
        .as_ref()
        .map(|s| {
            chrono::DateTime::parse_from_rfc3339(s)
                .map(|dt| dt.with_timezone(&Utc))
                .map_err(|e| Error::InvalidBundle(format!("Invalid expires timestamp: {e}")))
        })
        .transpose()?;

    Ok(BundleContents {
        label: payload.label,
        created,
        expires,
        bundle_id: payload.bundle_id,
        credentials: payload
            .credentials
            .into_iter()
            .map(|c| BundleCredential {
                domain: c.domain,
                url: c.url,
                username: c.username,
                password: c.password,
                credential_type: c.credential_type,
                label: c.label,
            })
            .collect(),
    })
}

/// Create an encrypted CredVault native bundle.
fn create_credvault_bundle(credentials: &[Credential], options: &BundleOptions) -> Result<Vec<u8>> {
    let payload = BundlePayload {
        label: options.label.clone(),
        created: Utc::now().to_rfc3339(),
        expires: options.expires.map(|d| d.to_rfc3339()),
        bundle_id: Uuid::new_v4().to_string(),
        credentials: credentials
            .iter()
            .map(|c| PayloadCredential {
                domain: c.entry.domain.clone(),
                url: c.entry.url.clone(),
                username: c.entry.username.clone(),
                password: c.secret.expose_secret().to_string(),
                credential_type: c.entry.credential_type,
                label: c.entry.label.clone(),
            })
            .collect(),
    };

    let serialized = rmp_serde::to_vec(&payload)
        .map_err(|e| Error::Serialization(format!("Failed to serialize bundle: {e}")))?;

    encrypt_bundle(&serialized, &options.password)
}

/// Create a CSV export (plaintext — user is warned).
fn create_csv_bundle(credentials: &[Credential]) -> Result<Vec<u8>> {
    let mut wtr = csv::Writer::from_writer(Vec::new());

    wtr.write_record(["domain", "url", "username", "password", "type"])
        .map_err(|e| Error::Serialization(e.to_string()))?;

    for cred in credentials {
        wtr.write_record([
            &cred.entry.domain,
            cred.entry.url.as_deref().unwrap_or(""),
            cred.entry.username.as_deref().unwrap_or(""),
            cred.secret.expose_secret(),
            &format!("{:?}", cred.entry.credential_type),
        ])
        .map_err(|e| Error::Serialization(e.to_string()))?;
    }

    wtr.into_inner()
        .map_err(|e| Error::Serialization(e.to_string()))
}

/// Create a .env file export.
fn create_env_bundle(credentials: &[Credential]) -> Result<Vec<u8>> {
    let mut output = String::new();
    output.push_str("# Generated by CredVault\n");
    output.push_str(&format!("# Created: {}\n\n", Utc::now().to_rfc3339()));

    for cred in credentials {
        let env_key = domain_to_env_key(&cred.entry.domain);

        if let Some(ref username) = cred.entry.username {
            output.push_str(&format!("{env_key}_USERNAME={username}\n"));
        }
        output.push_str(&format!(
            "{env_key}_PASSWORD={}\n",
            cred.secret.expose_secret()
        ));
        output.push('\n');
    }

    Ok(output.into_bytes())
}

/// Create an AI agent config JSON export.
fn create_agent_config_bundle(
    credentials: &[Credential],
    options: &BundleOptions,
) -> Result<Vec<u8>> {
    let config = serde_json::json!({
        "credvault_agent_config": {
            "version": 1,
            "bundle_id": Uuid::new_v4().to_string(),
            "created": Utc::now().to_rfc3339(),
            "expires": options.expires.map(|d| d.to_rfc3339()),
            "label": options.label,
            "credentials": credentials.iter().map(|c| {
                serde_json::json!({
                    "id": c.entry.id,
                    "domain": c.entry.domain,
                    "type": c.entry.credential_type,
                    "username": c.entry.username,
                    "password": c.secret.expose_secret(),
                    "url": c.entry.url,
                })
            }).collect::<Vec<_>>(),
            "permissions": {
                "can_rotate": false,
                "can_create_tokens": false,
            }
        }
    });

    serde_json::to_vec_pretty(&config).map_err(|e| Error::Serialization(e.to_string()))
}

/// Convert a domain name to an environment variable key.
fn domain_to_env_key(domain: &str) -> String {
    domain
        .to_uppercase()
        .replace('.', "_")
        .replace('-', "_")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_credentials() -> Vec<Credential> {
        vec![
            Credential {
                entry: CredentialEntry {
                    id: "test:login:0001".to_string(),
                    source_id: "test".to_string(),
                    credential_type: CredentialType::Password,
                    domain: "github.com".to_string(),
                    url: Some("https://github.com/login".to_string()),
                    username: Some("octocat".to_string()),
                    label: None,
                    created: None,
                    last_used: None,
                    modified: None,
                },
                secret: SecretString::from("gh-secret-123"),
            },
            Credential {
                entry: CredentialEntry {
                    id: "test:login:0002".to_string(),
                    source_id: "test".to_string(),
                    credential_type: CredentialType::Password,
                    domain: "aws.amazon.com".to_string(),
                    url: Some("https://console.aws.amazon.com/".to_string()),
                    username: Some("admin@acme.com".to_string()),
                    label: None,
                    created: None,
                    last_used: None,
                    modified: None,
                },
                secret: SecretString::from("aws-secret-456"),
            },
        ]
    }

    #[test]
    fn test_credvault_bundle_roundtrip() {
        let creds = sample_credentials();
        let password = SecretString::from("bundle-password-123");

        let options = BundleOptions {
            format: BundleFormat::CredVault,
            password: password.clone(),
            label: "Test Bundle".to_string(),
            expires: None,
            include_metadata: true,
        };

        let bundle_data = create_bundle(&creds, &options).unwrap();

        // Verify it starts with CVLT magic
        assert_eq!(&bundle_data[..4], b"CVLT");

        // Read it back
        let contents = read_bundle(&bundle_data, &password).unwrap();
        assert_eq!(contents.label, "Test Bundle");
        assert_eq!(contents.credentials.len(), 2);
        assert_eq!(contents.credentials[0].domain, "github.com");
        assert_eq!(contents.credentials[0].password, "gh-secret-123");
        assert_eq!(contents.credentials[1].domain, "aws.amazon.com");
        assert_eq!(contents.credentials[1].password, "aws-secret-456");
    }

    #[test]
    fn test_credvault_bundle_with_expiry() {
        let creds = sample_credentials();
        let password = SecretString::from("pw");

        let expires = Utc::now() + chrono::Duration::days(30);
        let options = BundleOptions {
            format: BundleFormat::CredVault,
            password: password.clone(),
            label: "Expiring Bundle".to_string(),
            expires: Some(expires),
            include_metadata: true,
        };

        let bundle_data = create_bundle(&creds, &options).unwrap();
        let contents = read_bundle(&bundle_data, &password).unwrap();

        assert!(contents.expires.is_some());
    }

    #[test]
    fn test_csv_export() {
        let creds = sample_credentials();
        let options = BundleOptions {
            format: BundleFormat::Csv,
            password: SecretString::from("unused"),
            label: "CSV".to_string(),
            expires: None,
            include_metadata: false,
        };

        let data = create_bundle(&creds, &options).unwrap();
        let csv_str = String::from_utf8(data).unwrap();

        assert!(csv_str.contains("domain,url,username,password,type"));
        assert!(csv_str.contains("github.com"));
        assert!(csv_str.contains("gh-secret-123"));
        assert!(csv_str.contains("aws.amazon.com"));
        assert!(csv_str.contains("aws-secret-456"));
    }

    #[test]
    fn test_env_export() {
        let creds = sample_credentials();
        let options = BundleOptions {
            format: BundleFormat::Env,
            password: SecretString::from("unused"),
            label: "ENV".to_string(),
            expires: None,
            include_metadata: false,
        };

        let data = create_bundle(&creds, &options).unwrap();
        let env_str = String::from_utf8(data).unwrap();

        assert!(env_str.contains("GITHUB_COM_USERNAME=octocat"));
        assert!(env_str.contains("GITHUB_COM_PASSWORD=gh-secret-123"));
        assert!(env_str.contains("AWS_AMAZON_COM_USERNAME=admin@acme.com"));
        assert!(env_str.contains("AWS_AMAZON_COM_PASSWORD=aws-secret-456"));
    }

    #[test]
    fn test_agent_config_export() {
        let creds = sample_credentials();
        let options = BundleOptions {
            format: BundleFormat::AgentConfig,
            password: SecretString::from("unused"),
            label: "Agent Config".to_string(),
            expires: None,
            include_metadata: true,
        };

        let data = create_bundle(&creds, &options).unwrap();
        let json: serde_json::Value = serde_json::from_slice(&data).unwrap();

        let config = &json["credvault_agent_config"];
        assert_eq!(config["version"], 1);
        assert_eq!(config["label"], "Agent Config");
        assert_eq!(config["credentials"].as_array().unwrap().len(), 2);
        assert_eq!(config["credentials"][0]["domain"], "github.com");
        assert_eq!(config["credentials"][0]["password"], "gh-secret-123");
    }

    #[test]
    fn test_domain_to_env_key() {
        assert_eq!(domain_to_env_key("github.com"), "GITHUB_COM");
        assert_eq!(domain_to_env_key("aws.amazon.com"), "AWS_AMAZON_COM");
        assert_eq!(
            domain_to_env_key("my-app.example.com"),
            "MY_APP_EXAMPLE_COM"
        );
    }
}
