[package]
name = "credvault-cli"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "credvault"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
clap.workspace = true
credvault-core = { path = "../credvault-core" }
secrecy.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
